name: "Format Code: ensure code formatting guidelines are met"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  format-code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: ministryofjustice/github-actions/code-formatter@83fe116532033aaedd6d4b4e269941c137f17497 # v18.2.5
        with:
            ignore-files: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
